WebPruebaTymesa/Models/Movimientos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WebPruebaTymesa.Models
{
    public class Movimientos
    {

        [Key]
        public int MovimientosID { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm:ss}", ApplyFormatInEditMode = false)]
        public DateTime Fecha { get; set; } = DateTime.Now;

        [NotMapped]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm:ss}", ApplyFormatInEditMode = false)]
        public DateTime FechaDesde { get; set; } = DateTime.Now;


        [NotMapped]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm:ss}", ApplyFormatInEditMode = false)]
        public DateTime FechaHasta { get; set; } = DateTime.Now;


        public int CuentasID { get; set; }

        public int TiposID { get; set; }

        [DataType(DataType.Currency)]
        [Required(ErrorMessage = "Ingrese el field {0}")]
        [Range(00, 999999999,
         ErrorMessage = "Value for {0} must be between {1} and {2}.")]
        public float Valor { get; set; }


        public virtual Cuentas Cuentas { get; set; }

        public virtual Tipos Tipos { get; set; }



    }
}

WebPruebaTymesa/Controllers/MovimientosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebPruebaTymesa.Data;
using WebPruebaTymesa.Models;

namespace WebPruebaTymesa.Controllers
{
    [Authorize]
    public class MovimientosController : Controller
    {
        private readonly ApplicationDbContext _context;
        readonly Funciones fn = new Funciones();
        public MovimientosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Movimientos
        public async Task<IActionResult> Index()
        {
         
            var usuario = User.Identity.Name;


            if (fn.Rol(_context, "ROLE_ADMIN", usuario))
            {
                return View(await _context.Movimientos.Include(m => m.Cuentas).Include(m => m.Tipos).Include(m => m.Cuentas.Clientes).OrderBy(c => c.Fecha).ToListAsync());
            }
            else
            {
               
                return View(await _context.Movimientos.Include(m => m.Cuentas).Include(m => m.Tipos).Include(m => m.Cuentas.Clientes).Where(c => c.Cuentas.Clientes.UserName == usuario).OrderBy(c => c.Fecha).ToListAsync());

            }





           
        }

        // GET: EstadoCuenta
        public async Task<IActionResult> EstadoCuenta(string Buscar, DateTime Fechai , DateTime Fechaf)
        {
            var applicationDbContext = _context.Movimientos.Include(m => m.Cuentas).Include(m => m.Tipos).Include(m => m.Cuentas.Clientes).Where(c=> c.Fecha.Date >= Fechai && c.Fecha.Date<= Fechaf.Date).OrderBy(c => c.Fecha);


            if (!string.IsNullOrEmpty(Buscar))
            {
                foreach (var item in Buscar.Split(new char[] { ' ' },
                         StringSplitOptions.RemoveEmptyEntries))
                {
                    applicationDbContext = applicationDbContext.Where(x => x.Cuentas.Clientes.Nombre.Contains(item))
                        .OrderBy(c=>c.Cuentas.Clientes.Nombre).ThenBy(c=>c.Fecha);
                                                  
                }
            }
            return View(await applicationDbContext.ToListAsync());
        
        }



        // GET: Movimientos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movimientos = await _context.Movimientos
                .Include(m => m.Cuentas)
                .Include(m => m.Tipos)
                .FirstOrDefaultAsync(m => m.MovimientosID == id);
            if (movimientos == null)
            {
                return NotFound();
            }

            return View(movimientos);
        }

        // GET: Movimientos/Create
        public IActionResult Create()
        {
            ViewData["CuentasID"] = new SelectList(_context.Cuentas, "CuentasID", "Numero");
            ViewData["TiposID"] = new SelectList(_context.Tipos, "TiposID", "Sigla");

            return View();
           
         
        }

        // POST: Movimientos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MovimientosID,Fecha,CuentasID,TiposID,Valor")] Movimientos movimientos)
        {
           
            if (ModelState.IsValid)
            {

                using (var transacction = _context.Database.BeginTransaction())
                {
                    try
                    {
                        movimientos.Fecha = DateTime.Now;
                        if (ActualizarSaldo(movimientos, out float _NewSaldo)) {

                            await _context.SaveChangesAsync();

                            _context.Add(movimientos);
                            await _context.SaveChangesAsync();

                             transacction.Commit();

                            return RedirectToAction(nameof(Index));

                        };


                        ViewBag.Error = "ERROR: " +"Saldo Insuficiente";
                        transacction.Rollback();
                     


                    }
                    catch (Exception ex)
                    {

                        if (ex.InnerException == null)
                        {
                            ViewBag.Error = "ERROR: " + ex.Message;
                        }
                        else
                        {
                            ViewBag.Error = "ERROR: " + ex.InnerException.InnerException.Message.ToString();
                        }
                     

                        transacction.Rollback();
                    }
                   
                }
              
            }
            ViewData["CuentasID"] = new SelectList(_context.Cuentas, "CuentasID", "Numero", movimientos.CuentasID);
            ViewData["TiposID"] = new SelectList(_context.Tipos, "TiposID", "Sigla", movimientos.TiposID);
            return View(movimientos);
        }

        private bool ActualizarSaldo(Movimientos movimientos,out float NewSaldo)
        {
            bool estado = true;
            int signo;
            float Saldo;
            var _Tipo = _context.Tipos.Find(movimientos.TiposID);
            signo = _Tipo.Signo;

            var _Cuenta = _context.Cuentas.Find(movimientos.CuentasID);
            Saldo = _Cuenta.Saldo + (movimientos.Valor * signo);

            NewSaldo = Saldo;

            if (Saldo < 0)
            {
                estado = false;
            }
            else
            {
                _Cuenta.Saldo = Saldo;
                _context.Update(_Cuenta);
                estado = true;
            }

          

            return estado;
        }

        // GET: Movimientos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movimientos = await _context.Movimientos.FindAsync(id);
            if (movimientos == null)
            {
                return NotFound();
            }
            ViewData["CuentasID"] = new SelectList(_context.Cuentas, "CuentasID", "CuentasID", movimientos.CuentasID);
            ViewData["TiposID"] = new SelectList(_context.Tipos, "TiposID", "Sigla", movimientos.TiposID);
            return View(movimientos);
        }

        // POST: Movimientos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MovimientosID,Fecha,CuentasID,TiposID,Valor")] Movimientos movimientos)
        {
            if (id != movimientos.MovimientosID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movimientos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovimientosExists(movimientos.MovimientosID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CuentasID"] = new SelectList(_context.Cuentas, "CuentasID", "CuentasID", movimientos.CuentasID);
            ViewData["TiposID"] = new SelectList(_context.Tipos, "TiposID", "Sigla", movimientos.TiposID);
            return View(movimientos);
        }

        // GET: Movimientos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movimientos = await _context.Movimientos
                .Include(m => m.Cuentas)
                .Include(m => m.Tipos)
                .FirstOrDefaultAsync(m => m.MovimientosID == id);
            if (movimientos == null)
            {
                return NotFound();
            }

            return View(movimientos);
        }

        // POST: Movimientos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movimientos = await _context.Movimientos.FindAsync(id);
            _context.Movimientos.Remove(movimientos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MovimientosExists(int id)
        {
            return _context.Movimientos.Any(e => e.MovimientosID == id);
        }
    }
}

WebPruebaTymesa/Views/Movimientos/Create.cshtml
@model WebPruebaTymesa.Models.Movimientos

@{
    ViewData["Title"] = "Create";



    string _Fecha = DateTime.Now.ToString("yyyy-MM-dd");
    //_Fecha = "2021-01-01";
}

<h3>Create</h3>

<h4>Movimientos</h4>

<h5 style="color:red">@ViewBag.Error</h5>
<h5>@ViewBag.Mensaje</h5>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" value=@_Fecha readonly="@(true)" />
                <span asp-validation-for="Fecha" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="CuentasID" class="control-label"></label>
                <select asp-for="CuentasID" class="form-control" asp-items="ViewBag.CuentasID"></select>
            </div>
            <div class="form-group">
                <label asp-for="TiposID" class="control-label"></label>
                <select asp-for="TiposID" class="form-control" asp-items="ViewBag.TiposID"></select>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebPruebaTymesa/Views/Movimientos/Delete.cshtml
@model WebPruebaTymesa.Models.Movimientos

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movimientos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Valor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cuentas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cuentas.CuentasID)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tipos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tipos.Sigla)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MovimientosID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebPruebaTymesa/Views/Movimientos/Details.cshtml
@model WebPruebaTymesa.Models.Movimientos

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Movimientos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Valor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cuentas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cuentas.CuentasID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tipos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tipos.Sigla)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.MovimientosID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebPruebaTymesa/Views/Movimientos/Edit.cshtml
@model WebPruebaTymesa.Models.Movimientos

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Movimientos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MovimientosID" />
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CuentasID" class="control-label"></label>
                <select asp-for="CuentasID" class="form-control" asp-items="ViewBag.CuentasID"></select>
                <span asp-validation-for="CuentasID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TiposID" class="control-label"></label>
                <select asp-for="TiposID" class="form-control" asp-items="ViewBag.TiposID"></select>
                <span asp-validation-for="TiposID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebPruebaTymesa/Views/Movimientos/EstadoCuenta.cshtml
@model IEnumerable<WebPruebaTymesa.Models.Movimientos>

@{
    ViewData["Title"] = "Index";
}

<h3>Estado de Cuenta</h3>


@{
    string format = "dd/MM/yyyy HH:mm:ss";
    var now = DateTime.Now.ToString(format);
    float Saldo = 0;
    float Debitos = 0;
    float Creditos = 0;
}




@*CÓDIGO PARA EL FILTRO DE BÚSQUEDA*@
<div class="text-right form-inline">
    <form method="get" action=@Url.Action("EstadoCuenta", "Movimientos" )>
        <div class="row" align="right">

            <div class="form-group">
                @Html.TextBox("buscar", null, new
                {
                    placeholder = "texto de búsqueda",
                                        @class = "form-control"
                })
            </div>


            <div class="form-group">
                <label>Desde</label>
                @Html.TextBox("Fechai", now, new
                {

                    placeholder = "Fecha Inicial",
                    @class = "form-control",
                    @type = "date",
                })
            </div>

            <div class="form-group">
                <label>Hasta</label>
                @Html.TextBox("Fechaf", now, new
                {

                    placeholder = "Fecha Final",
                    @class = "form-control",
                    @type = "date",
                })
            </div>


            <button class="btn-outline-info" type="submit">Buscar</button>
        </div>
    </form>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Fecha)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Cuentas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tipos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cuentas.Clientes.Nombre)
            </th>
            <th></th>
        </tr>

    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Fecha)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Cuentas.Numero)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tipos.Sigla)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Valor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cuentas.Clientes.Nombre)
                </td>
                <td>
                    @*<a asp-action="Edit" asp-route-id="@item.MovimientosID">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.MovimientosID">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.MovimientosID">Delete</a>*@
                </td>
            </tr>
            if (item.Tipos.Signo == 1)
            {
                Debitos += item.Valor;
            }
            else
            {
                Creditos += item.Valor;
            }

            Saldo += item.Valor * item.Tipos.Signo;
        }
    </tbody>
    <tfoot>
        @*<tr>
            <th>Debitos</th>
            <th>@Debitos</th>
            <th>Credito</th>
            <th>@Creditos</th>
            <th>Saldo</th>
            <th align="right">@Saldo.ToString("$###,###.00")</th>
        </tr>*@

    </tfoot>
</table>
<div class="row">
    <div class="col-md-2">Débitos</div>
    <div class="col-md-2">@Debitos.ToString("$###,###.00")</div>
    <div class="col-md-2">Crébitos</div>
    <div class="col-md-2">@Creditos.ToString("$###,###.00")</div>
    <div class="col-md-2">Saldo Final</div>
    <div class="col-md-2">@Saldo.ToString("$###,###.00")</div>
</div>



@section scripts {

    <script type="text/javascript">

        $(function () {

            $('#datepicker').datetimepicker({ format: 'YYYY/MM/DD' });


        });


    </script>
}

WebPruebaTymesa/Views/Movimientos/Index.cshtml
@model IEnumerable<WebPruebaTymesa.Models.Movimientos>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Fecha)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Cuentas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tipos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cuentas.Clientes.Nombre)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Fecha)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Cuentas.Numero)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tipos.Sigla)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Valor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cuentas.Clientes.Nombre)
                </td>
                <td>
                    @*<a asp-action="Edit" asp-route-id="@item.MovimientosID">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.MovimientosID">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.MovimientosID">Delete</a>*@
                </td>
            </tr>
        }
    </tbody>
</table>