WebPruebaTymesa/Controllers/ReporteMedicacionController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using WebPruebaTymesa.Data;
using WebPruebaTymesa.Models;

namespace WebPruebaTymesa.Controllers
{
    public class ReporteMedicacionController : Controller
    {
      
        private readonly ApplicationDbContext _context;

        private PaginadorGenerico<SP_F_ReporteMedicinas> _PaginadorCustomers;

        private readonly int _RegistrosPorPagina = 10;
        //  readonly Funciones fn = new Funciones();
        public ReporteMedicacionController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET: ReporteMedicacion
        public ActionResult Index(int pagina = 1)
        {
           
            int _TotalRegistros = 0;


            var _dato = _context.SP_F_ReporteMedicinas.FromSqlRaw("EXECUTE dbo.F_Reporte_MEdicinas")
             .ToList();


            // Número total de páginas de la tabla Customers
            _TotalRegistros = _dato.Count();

            // Obtenemos la 'página de registros' de la tabla Customers
            _dato = _dato.OrderBy(x => x.NombrePaciente)
                                             .Skip((pagina - 1) * _RegistrosPorPagina)
                                             .Take(_RegistrosPorPagina)
                                             .ToList();


            var _TotalPaginas = (int)Math.Ceiling((double)_TotalRegistros / _RegistrosPorPagina);
            // Instanciamos la 'Clase de paginación' y asignamos los nuevos valores
            _PaginadorCustomers = new PaginadorGenerico<SP_F_ReporteMedicinas>()
            {
                RegistrosPorPagina = _RegistrosPorPagina,
                TotalRegistros = _TotalRegistros,
                TotalPaginas = _TotalPaginas,
                PaginaActual = pagina,
                Resultado = _dato
            };
            // Enviamos a la Vista la 'Clase de paginación'
            return View(_PaginadorCustomers);
           

        }



        public ActionResult Indice()
        {
            //conexion



            var _dato = _context.SP_F_ReporteMedicinas.FromSqlRaw("EXECUTE dbo.F_Reporte_MEdicinas")
             .ToList();
            return View(_dato);

        }




    }
}

WebPruebaTymesa/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebPruebaTymesa</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebPruebaTymesa</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Banca</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                @Html.ActionLink("Clientes", "Index", "Clientes", null, new { @class = "dropdown-item" })
                                @Html.ActionLink("Cuentas", "Index", "Cuentas", null, new { @class = "dropdown-item" })
                                @Html.ActionLink("Movimientos", "Index", "Movimientos", null, new { @class = "dropdown-item" })
                                @Html.ActionLink("Estado de Cuenta", "EstadoCuenta", "Movimientos", null, new { @class = "dropdown-item" })

                            </ul>
                        </li>

                        <li class="dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Salud</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                @Html.ActionLink("Reporte Medicacion", "Index", "ReporteMedicacion", null, new { @class = "dropdown-item" })


                            </ul>
                        </li>

                        <li class="dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Archivo</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                @Html.ActionLink("Bitacora", "Index", "Bitacora", null, new { @class = "dropdown-item" })


                            </ul>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebPruebaTymesa - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>